### ISSUE TITLE
一直显示正在初始化

### ISSUE THREAD

**Issue by zhangqib** [N0I0C0K/PowerToysRun.Plugin.Translater#10]
[![R53Gt.png](https://i.328888.xyz/2023/02/11/R53Gt.png)](https://imgloc.com/i/R53Gt)

按照说明把文件放在Plugin目录下之后就一直显示正在初始化

**Comment by N0I0C0K** [comment]
这个时候按下`Esc`再重新按`alt+Space` 打开就行了. 

如果这样还有问题可以尝试:
- 升级到最新版本的PowerToys
- 重新启动PowerToys

如果依旧没有解决, 麻烦和我说一声我来解决

**Comment by zhangqib** [comment]
> 这个时候按下`Esc`再重新按`alt+Space` 打开就行了.
> 
> 如果这样还有问题可以尝试:
> 
> * 升级到最新版本的PowerToys
> * 重新启动PowerToys
> 
> 如果依旧没有解决, 麻烦和我说一声我来解决

已经尝试过你提到的所有解决方案, 但是依然没有解决. 我的powertoys版本为`v0.67.1`, 显示是最新.
还是一样的正在初始化, 我怀疑是`YoudaoTranslater`的初始化问题, 是否有查看log的方法

**Comment by N0I0C0K** [comment]
有, 前往`{User}\AppData\Local\Microsoft\PowerToys\PowerToys Run\Logs\0.67.1.0`将最新的log发送一份

**Comment by N0I0C0K** [comment]
你是还未开始使用就出现这个问题, 还是你已经使用了一段时间了,中途出现的此问题

**Comment by zhangqib** [comment]
> 你是还未开始使用就出现这个问题, 还是你已经使用了一段时间了,中途出现的此问题

昨天刚装上就这样, 我今天试了下还是这样子

**Comment by zhangqib** [comment]
> 有, 前往`{User}\AppData\Local\Microsoft\PowerToys\PowerToys Run\Logs\0.67.1.0`将最新的log发送一份


[2023-02-11 14:30:27.3363] [WARN] [C:\aaa_program\Translater\src\TranslateHelper.cs::107]
请求的名称有效，但是找不到请求的类型的数据。 (rlogs.youdao.com:443)

[2023-02-11 14:33:12.7099] [WARN] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::207]
PluginManager.QueryForPlugin Windows Indexer. Query cost - 197 milliseconds

[2023-02-11 14:33:14.5123] [WARN] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::207]
PluginManager.QueryForPlugin Windows Indexer. Query cost - 502 milliseconds

[2023-02-11 14:33:14.5430] [WARN] [C:\a\_work\1\s\src\modules\launcher\PowerLauncher\Plugin\PluginManager.cs::207]
PluginManager.QueryForPlugin Windows Indexer. Query cost - 781 milliseconds

[2023-02-11 14:33:15.9836] [WARN] [C:\aaa_program\Translater\src\TranslateHelper.cs::107]
请求的名称有效，但是找不到请求的类型的数据。 (rlogs.youdao.com:443)

[2023-02-11 14:33:18.9878] [WARN] [C:\aaa_program\Translater\src\TranslateHelper.cs::107]
请求的名称有效，但是找不到请求的类型的数据。 (rlogs.youdao.com:443)

**Comment by N0I0C0K** [comment]
你把log文件拖入输入框全部传输我下载下来看

**Comment by zhangqib** [comment]
[2023-02-11.txt](https://github.com/N0I0C0K/PowerToysRun.Plugin.Translater/files/10712948/2023-02-11.txt)

**Comment by N0I0C0K** [comment]
好的, 感谢反馈, 我分析完后回复

**Comment by zhangqib** [comment]
> 好的, 感谢反馈, 我分析完后回复

好的 谢谢回复

**Comment by N0I0C0K** [comment]
问一下是有开全局代理吗

**Comment by zhangqib** [comment]
我没有全局代理
我尝试了
- 关闭代理,
- 关闭代理, 重启应用
- 切换网络
- 切换网络, 重启应用

依然都是原来的样子, 无法使用

**Comment by N0I0C0K** [comment]
也就是截至目前为止, 你没有成功查询过一次. 一直都是初始化对吗

**Comment by zhangqib** [comment]
> 也就是截至目前为止, 你没有成功查询过一次. 一直都是初始化对吗

对

**Comment by N0I0C0K** [comment]
我在本地多次尝试复现问题无果, 没有出现这个问题. 但是按照我的分析可能是有道这个接口封锁了一个ip段. 按照以往的经验一天就会解封.

我给出以下建议:

1. 关闭插件 
![image](https://user-images.githubusercontent.com/30338746/218257159-a3429ab0-334b-4e57-b3c9-bb57612f809d.png)
2. 第二天再打开插件

**Comment by N0I0C0K** [comment]
如果依旧没有解决, 可以继续反馈

**Comment by N0I0C0K** [comment]
请问问题解决了吗

**Comment by zhangqib** [comment]
> 请问问题解决了吗

依然没有
[2023-02-13.txt](https://github.com/N0I0C0K/PowerToysRun.Plugin.Translater/files/10719164/2023-02-13.txt)

**Comment by N0I0C0K** [comment]
方便加一下我的私人联系方式吗, 方便沟通解决 (qq:1481197447)

**Comment by N0I0C0K** [comment]
此问题最后发现是因为网络原因导致. 

如果有相同问题, 可以去 [有道翻译](https://fanyi.youdao.com/index.html#/) 尝试网页翻译, 如果网页端无法翻译应该就是网络问题,
