### ISSUE TITLE
开发一个类似于Alfred中历史剪切板的插件

### ISSUE THREAD

**Issue by Zeke-chin** [N0I0C0K/PowerToysRun.Plugin.Translater#11]
开发者你好，首先十分感谢你开发了这个插件，并且我为国人能开发这么好用的插件为荣！！
插件建议：
1. 添加多翻译引擎配置入口
2. (这个我不太懂有没有办法实现) 更改呼出翻译栏快捷键，如自定义Alt+t 呼出

写在后面：
我是一个初级py/go开发者，我想开发一个历史剪切板的插件，想请教一下开发PowerToysRun的插件是否必须使用c#.
可能是我的信息检索能力太弱了，并没有找到官方插件开发指南，只找到了[开发规范](https://github.com/microsoft/PowerToys/wiki/PowerToys-Run-Plugin-spec)，想请教一下有没有开发指南，或者您是如何开发的

**Comment by N0I0C0K** [comment]
首先, 很高兴你喜欢这个插件! 


关于你提及的建议我给出以下答复

- > 添加多翻译引擎配置入口

首先插件内已内置了3个翻译接口稳定性还是不错的. 其次是目前Powertoys Run插件接口只提供了bool类型的自定义设置字段, 所以目前手动配置接口无法实现. 但是后期Powertoys Run会开放其他类型的自定义字段, 届时就会实现相关功能.

- >更改呼出翻译栏快捷键，如自定义Alt+t 呼出

这个我没有理解清楚, 你是想`alt+t`直接调出翻译吗. 如果是这样的画, 有一个不完美的方案就是勾选插件的`包括在全局结果中`.

- > 开发PowerToysRun的插件是否必须使用c#

是的, 目前是只能C#开发. 关于插件的开发指南目前官方并没有写道. 但是因为Powertoys Run是基于[Wox](https://github.com/Wox-launcher/Wox). 所以可以参考Wox的[插件开发](http://doc.wox.one/zh/plugin/csharp_plugin.html). 需要注意的是插件开发需要和官方的net版本一致. 后期我考虑出一个插件开发模板.

- >历史剪切板的插件

关于这个功能, windows已经内置了这个功能, 你可以尝试按下`win+v`就可以打开历史剪切板. 但是如果你有什么不同的想法我非常支持你实现!

**Comment by Zeke-chin** [comment]
好的，那我去研究一下Wox的插件开发指南
> 剪切板功能描述

windows内置的功能对于我来说可能过于简单了我想要更加高级一些的剪切板功能 甚至集成收藏功能。具体可以参考[Alfred中的剪切板功能](https://zhuanlan.zhihu.com/p/33515314)

> 快捷键说明

现在激活方式 `alt+space` ->呼出 `PowerToys Run` ->输入`&` -> 输入"Hello" ==>出现翻译结果"你好"

我希望的激活方式 `alt+t` -> 呼出 `翻译版PowerToys Run` ->输入"Hello" ==>出现翻译结果"你好"

**Comment by Zeke-chin** [comment]
我想在wox中应该是可以的，
![image](https://user-images.githubusercontent.com/84116651/221393587-a1aa787c-cb23-4b75-b8f7-ef4a1e7e26d2.png)
之前也用过一段时间wox，但是并没有仔细阅读过他的文档，感谢！！

**Comment by N0I0C0K** [comment]
> 我想在wox中应该是可以的， ![image](https://user-images.githubusercontent.com/84116651/221393587-a1aa787c-cb23-4b75-b8f7-ef4a1e7e26d2.png) 之前也用过一段时间wox，但是并没有仔细阅读过他的文档，感谢！！

热键这个功能确实很不错! 可惜Powertoys Run目前还没有开放接口, 预计后期会添加. 届时我会更新相关功能!

**Comment by N0I0C0K** [comment]
> 好的，那我去研究一下Wox的插件开发指南
> 
> > 剪切板功能描述
> 
> windows内置的功能对于我来说可能过于简单了我想要更加高级一些的剪切板功能 比如搜索功能等。具体可以参考[Alfred中的剪切板功能](https://zhuanlan.zhihu.com/p/33515314)
> 
> > 快捷键说明
> 
> 现在激活方式 `alt+space` ->呼出 `PowerToys Run` ->输入`&` -> 输入"Hello" ==>出现翻译结果"你好"
> 
> 我希望的激活方式 `alt+t` -> 呼出 `翻译版PowerToys Run` ->输入"Hello" ==>出现翻译结果"你好"

剪贴板搜索确实是个不错的想法! Wox有类似的插件可以参考一下, [Clipboard History](http://www.wox.one/plugin/4).

**Comment by Zeke-chin** [comment]
> > 好的，那我去研究一下Wox的插件开发指南
> > > 剪切板功能描述
> > 
> > 
> > windows内置的功能对于我来说可能过于简单了我想要更加高级一些的剪切板功能 比如搜索功能等。具体可以参考[Alfred中的剪切板功能](https://zhuanlan.zhihu.com/p/33515314)
> > > 快捷键说明
> > 
> > 
> > 现在激活方式 ->呼出 ->输入 -> 输入“Hello” ==>出现翻译结果“你好”`alt+space``PowerToys Run``&`
> > 我希望的激活方式 -> 呼出 ->输入“Hello” ==>出现翻译结果“你好”`alt+t``翻译版PowerToys Run`
> 
> 剪贴板搜索确实是个不错的想法!Wox有类似的插件可以参考一下， [Clipboard History](http://www.wox.one/plugin/4).

好的 感谢！！
