### ISSUE TITLE
在使用everything插件时,发现^符号冲突

### ISSUE THREAD

**Issue by Gaia-X-Alter** [N0I0C0K/PowerToysRun.Plugin.Translater#4]
在使用everything插件时,发现^符号冲突,导致插件无效且无任何报错

everything 插件地址:https://github.com/IzaiahSun/PowerToys/releases/tag/1.0.0

<img width="500" alt="1" src="https://user-images.githubusercontent.com/25919004/214671380-5077bce3-05a4-44a8-b66c-e5d0bb9a5b28.png">

------------------
修改json配置为 !后,功能正常
考虑到单手使用,输入^ 实在不方便,建议作者修改默认配置,同时追加报错说明
![image](https://user-images.githubusercontent.com/25919004/214672488-3477576a-e27a-4ff8-a549-583da0bdbf46.png)

======-======-=====-=-=

一些使用感受

1. 虽然有自动黏贴剪贴板功能,但是在输入栏已有词的情况下,输入栏默认显示上次查询结果,此时界面为
![image](https://user-images.githubusercontent.com/25919004/214689464-cd9f5e66-1288-46f9-9a58-94bc76cae46f.png)
剪贴板为:"自"
这时候,需要删掉ActionKeyword,再键入一次,即删除"!"再输入"!",才能显示正确结果
![image](https://user-images.githubusercontent.com/25919004/214690820-98c6247f-d12c-4119-ad0c-cccfb9295cb4.png)

临时方案:使用auto hotkey脚本,整合所有操作
```F3::Send ^c!{Space}{!} ```
该命令使用 F3 发送 ctrl+c alt+space "!",达成`一键翻译-哪里不会点哪里`
效果如下

![1](https://user-images.githubusercontent.com/25919004/214698468-0ad12ca6-9907-4ae5-a845-75c9e814f038.gif)

建议:在输入栏出现时,加个刷新,这样每次查词只需要两个操作-->ctrl+c,alt+space

=
2. 有时候有道那边http出错,需要重启整个power toys才能正常显示,还有的时候,莫名其妙power toys死掉,也需要重启

3.可以考虑加个收藏(star),关联个sqlite,记录一下查词时间等等,方便复习

4.把修改ActionKeyword加到ui里

**Comment by N0I0C0K** [comment]
1. 关于触发按键, 你应该是没有看到这个, 可以直接在这里修改. 这个是默认自带的
![image](https://user-images.githubusercontent.com/30338746/214745407-467b6b84-d3fa-48f2-a684-fc7ff3ff9757.png)
2. 默认上次的搜索内容, 我有一个解决办法(可能是临时的)就是勾选`在启动时清楚上一次查询`, 我还会继续寻找这个问题的原因
![image](https://user-images.githubusercontent.com/30338746/214745583-2fa4c72e-8484-416d-8ff8-7329fd54fccc.png)
3. http出错下一次可以截一下图片👀方便我看一下什么原因. 但是我猜测应该是有道翻译有小概率不稳定导致的.
4. 会导致powertoys 死掉的问题我会去修复.
5. 加一个star的功能非常不错! 最近会去实现

**Comment by Gaia-X-Alter** [comment]
> 1. 关于触发按键, 你应该是没有看到这个, 可以直接在这里修改. 这个是默认自带的. 将默认触发按键改为`!`的提议不太行, 因为插件`Windows 服务`已经占用

√:确实,不过还是建议右半边键盘找个合适的,比如`#`,原来的`!`也会和everything插件冲突,这个UI已经有了确实我没看到,不好意思

> 2. 默认上次的搜索内容, 我有一个解决办法(可能是临时的)就是勾选`在启动时清楚上一次查询`, 我还会继续寻找这个问题的原因

--:理想情况是尽量减少输入,使用auto hotkey 是可以一次触发,无需再输入,反馈里有提到,考虑到其他用户可能不用auto hotkey,还有个别程序对auto hotkey支持,以及配合power toys Ocr工具

目前勾选`在启动时清除上一次查询`仍需要输入 `选中待翻译字符串`+`ctrl+c`+`alt+space`+`ActionKeyword`才能获得结果,相较于默认情况少输入一次`backspace`
这一点上可能还需要再研究,总之,目的就是用最少的输入获得结果,哪怕能少按一次按键,对长期使用的总体效率都是巨大提升

> 3. http出错下一次可以截一下图片👀方便我看一下什么原因. 但是我猜测应该是有道翻译有小概率不稳定导致的.

√:下次发生后会进行截图,如果可能的话,尽量还是使用离线词库,比如google等离线词库

> 4. 会导致powertoys 死掉的问题我会去修复.

√
> 5. 加一个star的功能非常不错! 最近会去实现

√

**Comment by N0I0C0K** [comment]
> 目前勾选在启动时清除上一次查询仍需要输入 ctrl+c+alt+space+Shift+6(ActionKeyword:^) 总共进行5次按键,才能获得结果,相较于默认情况少输入一次backspace......
确实, 更少的按键会有更好的体验, 我会继续去研究一下如何快速触发.

**Comment by Gaia-X-Alter** [comment]
在文献翻阅中,高强度,高频词使用插件,发现了新的问题:

1.在手动输入(即不使用黏贴),无崩溃情况下,插件失效,此时输入`ActionKeyword`未能唤起,界面如下所示
![image](https://user-images.githubusercontent.com/25919004/214776403-f8d321b3-65bc-4fc4-a038-9df3f96bcf8c.png)
需要清除输入框,再重复打开输入框->`alt+space`,稍等一段时间(5-6s)进行输入,才能正常使用
![image](https://user-images.githubusercontent.com/25919004/214776584-565fe22f-2131-479d-a3f5-69467c61f13a.png)
该问题出现次数非常频繁,大概每查询10个字符串左右就会反复出现,不知道是否和请求超时有关

**Comment by N0I0C0K** [comment]
这个问题确实是会被这个情况(长时间短间隔多次请求)触发, 目前我猜测是因为有道翻译有一些限制, 近期也在着手解决这个问题.
目前这个问题除了可以切换ip, 还可能等到第二天就可以恢复.

**Comment by Gaia-X-Alter** [comment]
> 这个问题确实是会被这个情况(长时间短间隔多次请求)触发, 目前我猜测是因为有道翻译有一些限制, 近期也在着手解决这个问题. 目前这个问题除了可以切换ip, 还可能等到第二天就可以恢复.

可能要考虑一下请求频率问题了,在使用过程我发现,输入`""test"` 字符串,则在`"t"`的时候会请求两次,`"te"`的时候也会请求一次,然后`"test"`输入完毕后又请求了一次,算前置的一些准备,总共请求6次,具体情况如下
![1](https://user-images.githubusercontent.com/25919004/214800523-78d424f3-5e3e-4d82-a216-abdd41f6cb7d.gif)

**Comment by N0I0C0K** [comment]
这个是考虑到了的, 并且在代码里面是实现了的, 但是为了兼顾<反应迅速>做出了一些取舍. 对于输入较慢的用户确实会出现多次请求, 但是输入较快的用户基本不会出现多次请求. 本来是打算把查询延迟提供出来自己配置, 但是目前Powertoys Run支持的自定义设置类型只有bool类型. 这个确实也需要改进!

**Comment by Gaia-X-Alter** [comment]
> 这个是考虑到了的, 并且在代码里面是实现了的, 但是为了兼顾<反应迅速>做出了一些取舍. 对于输入较慢的用户确实会出现多次请求, 但是输入较快的用户基本不会出现多次请求. 本来是打算把查询延迟提供出来自己配置, 但是目前Powertoys Run支持的自定义设置类型只有bool类型. 这个确实也需要改进!

√

**Comment by N0I0C0K** [comment]
感谢你发现问题并且提出建议 !🚀
