### ISSUE TITLE
默认的激活命令可以改为+-*/这种在中文输入法下和英文输出一致的字符更加方便

### ISSUE THREAD

**Issue by sage9731** [N0I0C0K/PowerToysRun.Plugin.Translater#5]
默认的激活命令可以改为+-*/这种在中文输入法下和英文输出一致的字符更加方便。

当前的激活命令^在中文输入下是……，如果要翻译中文的话，需要打开power toys run，切成英文，按下shift+6输出^，再切成中文输入，输入需要翻译的词语，步骤相当麻烦。

如果是+-*/这些字符作为激活命令的话，只需要打开power toys run，按下对应按键，输入需要翻译的词语，不用为了输入激活命令去切换为英文输入。

**Comment by sage9731** [comment]
+ 和 * 需要在有小键盘的情况才比较方便，可选的就只有 / 和 - 了

**Comment by N0I0C0K** [comment]
> 当前的激活命令^在中文输入下是……

确实, 在中文输入下需要多按一下. 这是一个很大的问题.  我发现我之前之没有发现这个问题, 是因为我勾选了`中文输入使用英文标点`这个设置
![image](https://user-images.githubusercontent.com/30338746/215425013-35fad685-fe76-4f28-b01c-2f0380ff2016.png)

这样可以解决多按一次的问题, 但是考虑到还是有很多人需要中文标点符号, 所以这确实不是一个优雅的解决方案.

确实有考虑到换一个默认触发按键, 我目前比较理想的是字母`t`
然后每次使用`t 你好->ja`
