### ISSUE TITLE
一直在initializing

### ISSUE THREAD

**Issue by FranklinBC** [N0I0C0K/PowerToysRun.Plugin.Translater#8]
如题，将translater放入plugin文件夹后重启powertoys，发现输入^后一直显示initializing，插件无法正常使用。
powertoys版本0.67.0

**Comment by FranklinBC** [comment]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/98698077/217761027-b79ca817-71f9-40d4-a73f-71a482a34cdf.png">

**Comment by N0I0C0K** [comment]
我在我本地0.67.1下没有发现此问题

- 建议升级到最新版本
- 尝试一下关闭PowerToys 然后重新启动

希望能够帮助到你.

**Comment by N0I0C0K** [comment]
请问问题解决了吗

**Comment by FranklinBC** [comment]
问题不再出现了，谢谢
